### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by YoumyTheGoust** [aglorice/new_xxt#16]
exe运行起来后选择获取课程等其他功能的时候闪退
使用源码通过终端启动后选择获取课程等其他功能时报错
Traceback (most recent call last):
  File "D:\Users\小严家的彭彭\Desktop\TK\new_xxt-red\new_xxt-red\my_xxt\api.py", line 177, in getCourse
    "course_url": course_div.a.attrs['href'],
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attrs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\小严家的彭彭\Desktop\TK\new_xxt-red\new_xxt-red\main.py", line 14, in <module>
    select_menu(console, xxt)
  File "D:\Users\小严家的彭彭\Desktop\TK\new_xxt-red\new_xxt-red\my_xxt\my_tools.py", line 93, in select_menu
    courses = xxt.getCourse()
              ^^^^^^^^^^^^^^^
  File "D:\Users\小严家的彭彭\Desktop\TK\new_xxt-red\new_xxt-red\my_xxt\api.py", line 187, in getCourse
    "course_url": course_div.a.attrs['href'],
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attrs'

**Comment by aglorice** [comment]
该账号的是否有课程信息啊，我测试了我自己的账号，发现是没有问题的

**Comment by YoumyTheGoust** [comment]
有课程信息的哦，我是在win系统上运行的，是不是运行环境的问题

**Comment by aglorice** [comment]
应该不是环境的问题，我改了下， [fix: 优化对课程信息为空的异常处理](https://github.com/aglorice/new_xxt/commit/7673a4104bb9eef43a8ef051d7c5aa1ac8956a4e)，不知道能否解决
